import { Poppins } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`dark ${poppins.variable}`}>
      <head />
      <body className="antialiased">
        <Script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="3aabfa19-c9b7-4e41-95f3-a65817975c25"
        />
        {children}
      </body>
    </html>
  );
}
